"""L5 per-n file generator.

Emits one Lean file `Cbcert/FiniteLaw/N<n>.lean` per n in a requested range, each
proving the corrected Brown-Zudilin law at n against the project's CANONICAL
`pn`/`d` definitions.  All witnesses (the exact rational value of `pn n`, the
lcm `d n`, the central binomial `C(2n,n)`, and the integer `M = 12*d^5*P_n`) are
computed here in exact Fraction arithmetic and inlined as literals, so the Lean
kernel only has to CHECK, not search.

Usage:
    python3 l5_gen.py NSTART NEND [--outdir DIR]

Each file `N<n>.lean` proves:
    pn_val_<n>    : pn n = <literal>          (the expensive kernel reduction)
    pn_ne_zero_<n>: pn n ≠ 0                  (free byproduct)
    law_<n>       : CorrectedLaw n            (∃ m, 12*d_n^5*P_n = m; m literal)

The generator also (re)writes the aggregation stub is left to FiniteLaw.lean; it
prints the list of n it generated so the caller can wire imports/aggregate.
"""

import argparse
import os
from fractions import Fraction
from math import comb

# Reuse the exact-arithmetic construction from the gate (same directory).
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from l5_gate import pn_of, lcm_upto  # noqa: E402


def witness(n):
    """Return (pn, d, C, M) in exact arithmetic; assert M is an integer."""
    pn = pn_of(n)
    d = lcm_upto(n)
    C = comb(2 * n, n)
    P = Fraction((-1) ** (n + 1)) * pn / C
    law = 12 * Fraction(d) ** 5 * P
    assert law.denominator == 1, f"law_{n} is NOT an integer: {law} -- FALSIFIED"
    return pn, d, C, int(law)


FILE_TEMPLATE = '''\
import Cbcert.FiniteLaw

/-! # L5 corrected-law verification at `n = {n}`.

Auto-generated by `scripts/l5_gen.py` (exact-arithmetic witnesses).
Witness `M = {M}` ({Mdigits} digits); `d_{n} = {d}`, `C(2·{n},{n}) = {C}`.
`law_{n}` upgrades `Main.pn_valuation`'s disjunct to the sharp form at `n = {n}`
(via `pn_ne_zero_{n}`). Do not edit by hand. -/

namespace Cbcert.FiniteLaw

open Cbcert

set_option maxHeartbeats 400000000
set_option maxRecDepth 8000

/-- Canonical `pn {n}`, kernel-reduced from the `Bseries`/`acoeff` construction. -/
theorem pn_val_{n} : pn {n} = {pnnum} / {pnden} := by eval_pn

/-- `pn {n} ≠ 0` — sharp-disjunct upgrade for `Main.pn_valuation` at `n = {n}`. -/
theorem pn_ne_zero_{n} : pn {n} ≠ 0 := by rw [pn_val_{n}]; norm_num

/-- The corrected law `12·d_{n}⁵·P_{n} = {M} ∈ ℤ`. -/
theorem law_{n} : CorrectedLaw {n} :=
  law_of_vals {n} {M} {d} {C} ({pnnum} / {pnden})
    (by decide) (by decide) pn_val_{n} (by norm_num)

end Cbcert.FiniteLaw
'''


def emit(n, outdir):
    pn, d, C, M = witness(n)
    body = FILE_TEMPLATE.format(
        n=n, M=M, Mdigits=len(str(abs(M))), d=d, C=C,
        pnnum=pn.numerator, pnden=pn.denominator,
    )
    path = os.path.join(outdir, f"N{n}.lean")
    with open(path, "w") as fh:
        fh.write(body)
    return path, M


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("nstart", type=int)
    ap.add_argument("nend", type=int)
    ap.add_argument("--outdir", default=None,
                    help="output dir (default: ../Cbcert/FiniteLaw relative to this script)")
    args = ap.parse_args()
    if args.outdir is None:
        here = os.path.dirname(os.path.abspath(__file__))
        args.outdir = os.path.normpath(os.path.join(here, "..", "Cbcert", "FiniteLaw"))
    os.makedirs(args.outdir, exist_ok=True)
    ns = list(range(args.nstart, args.nend + 1))
    for n in ns:
        path, M = emit(n, args.outdir)
        print(f"wrote {path}  (M has {len(str(abs(M)))} digits)")
    print("generated n =", ns)


if __name__ == "__main__":
    main()
