import Cbcert.FiniteLaw

/-! # L5 corrected-law verification at `n = 2`.

Auto-generated by `scripts/l5_gen.py` (exact-arithmetic witnesses).
Witness `M = 1190161` (7 digits); `d_2 = 2`, `C(2·2,2) = 6`.
`law_2` upgrades `Main.pn_valuation`'s disjunct to the sharp form at `n = 2`
(via `pn_ne_zero_2`). Do not edit by hand. -/

namespace Cbcert.FiniteLaw

open Cbcert

set_option maxHeartbeats 400000000
set_option maxRecDepth 8000

/-- Canonical `pn 2`, kernel-reduced from the `Bseries`/`acoeff` construction. -/
theorem pn_val_2 : pn 2 = -1190161 / 64 := by eval_pn

/-- `pn 2 ≠ 0` — sharp-disjunct upgrade for `Main.pn_valuation` at `n = 2`. -/
theorem pn_ne_zero_2 : pn 2 ≠ 0 := by rw [pn_val_2]; norm_num

/-- The corrected law `12·d_2⁵·P_2 = 1190161 ∈ ℤ`. -/
theorem law_2 : CorrectedLaw 2 :=
  law_of_vals 2 1190161 2 6 (-1190161 / 64)
    (by decide) (by decide) pn_val_2 (by norm_num)

end Cbcert.FiniteLaw
