import Cbcert.FiniteLaw

/-! # L5 corrected-law verification at `n = 3`.

Auto-generated by `scripts/l5_gen.py` (exact-arithmetic witnesses).
Witness `M = 69138191151` (11 digits); `d_3 = 6`, `C(2·3,3) = 20`.
`law_3` upgrades `Main.pn_valuation`'s disjunct to the sharp form at `n = 3`
(via `pn_ne_zero_3`). Do not edit by hand. -/

namespace Cbcert.FiniteLaw

open Cbcert

set_option maxHeartbeats 400000000
set_option maxRecDepth 8000

/-- Canonical `pn 3`, kernel-reduced from the `Bseries`/`acoeff` construction. -/
theorem pn_val_3 : pn 3 = 38410106195 / 2592 := by eval_pn

/-- `pn 3 ≠ 0` — sharp-disjunct upgrade for `Main.pn_valuation` at `n = 3`. -/
theorem pn_ne_zero_3 : pn 3 ≠ 0 := by rw [pn_val_3]; norm_num

/-- The corrected law `12·d_3⁵·P_3 = 69138191151 ∈ ℤ`. -/
theorem law_3 : CorrectedLaw 3 :=
  law_of_vals 3 69138191151 6 20 (38410106195 / 2592)
    (by decide) (by decide) pn_val_3 (by norm_num)

end Cbcert.FiniteLaw
