import Cbcert.FiniteLaw

/-! # L5 corrected-law verification at `n = 4`.

Auto-generated by `scripts/l5_gen.py` (exact-arithmetic witnesses).
Witness `M = 673482301674435` (15 digits); `d_4 = 12`, `C(2·4,4) = 70`.
`law_4` upgrades `Main.pn_valuation`'s disjunct to the sharp form at `n = 4`
(via `pn_ne_zero_4`). Do not edit by hand. -/

namespace Cbcert.FiniteLaw

open Cbcert

set_option maxHeartbeats 400000000
set_option maxRecDepth 8000

/-- Canonical `pn 4`, kernel-reduced from the `Bseries`/`acoeff` construction. -/
theorem pn_val_4 : pn 4 = -873032613281675 / 55296 := by eval_pn

/-- `pn 4 ≠ 0` — sharp-disjunct upgrade for `Main.pn_valuation` at `n = 4`. -/
theorem pn_ne_zero_4 : pn 4 ≠ 0 := by rw [pn_val_4]; norm_num

/-- The corrected law `12·d_4⁵·P_4 = 673482301674435 ∈ ℤ`. -/
theorem law_4 : CorrectedLaw 4 :=
  law_of_vals 4 673482301674435 12 70 (-873032613281675 / 55296)
    (by decide) (by decide) pn_val_4 (by norm_num)

end Cbcert.FiniteLaw
