import Cbcert.FiniteLaw

/-! # L5 corrected-law verification at `n = 5`.

Auto-generated by `scripts/l5_gen.py` (exact-arithmetic witnesses).
Witness `M = 736880280072984117027` (21 digits); `d_5 = 60`, `C(2·5,5) = 252`.
`law_5` upgrades `Main.pn_valuation`'s disjunct to the sharp form at `n = 5`
(via `pn_ne_zero_5`). Do not edit by hand. -/

namespace Cbcert.FiniteLaw

open Cbcert

set_option maxHeartbeats 400000000
set_option maxRecDepth 8000

/-- Canonical `pn 5`, kernel-reduced from the `Bseries`/`acoeff` construction. -/
theorem pn_val_5 : pn 5 = 573129106723432091021 / 28800000 := by eval_pn

/-- `pn 5 ≠ 0` — sharp-disjunct upgrade for `Main.pn_valuation` at `n = 5`. -/
theorem pn_ne_zero_5 : pn 5 ≠ 0 := by rw [pn_val_5]; norm_num

/-- The corrected law `12·d_5⁵·P_5 = 736880280072984117027 ∈ ℤ`. -/
theorem law_5 : CorrectedLaw 5 :=
  law_of_vals 5 736880280072984117027 60 252 (573129106723432091021 / 28800000)
    (by decide) (by decide) pn_val_5 (by norm_num)

end Cbcert.FiniteLaw
