import Cbcert.FiniteLaw

/-! # L5 corrected-law verification at `n = 6`.

Auto-generated by `scripts/l5_gen.py` (exact-arithmetic witnesses).
Witness `M = 282653756112686336975107` (24 digits); `d_6 = 60`, `C(2·6,6) = 924`.
`law_6` upgrades `Main.pn_valuation`'s disjunct to the sharp form at `n = 6`
(via `pn_ne_zero_6`). Do not edit by hand. -/

namespace Cbcert.FiniteLaw

open Cbcert

set_option maxHeartbeats 400000000
set_option maxRecDepth 8000

/-- Canonical `pn 6`, kernel-reduced from the `Bseries`/`acoeff` construction. -/
theorem pn_val_6 : pn 6 = -21764339220676847947083239 / 777600000 := by eval_pn

/-- `pn 6 ≠ 0` — sharp-disjunct upgrade for `Main.pn_valuation` at `n = 6`. -/
theorem pn_ne_zero_6 : pn 6 ≠ 0 := by rw [pn_val_6]; norm_num

/-- The corrected law `12·d_6⁵·P_6 = 282653756112686336975107 ∈ ℤ`. -/
theorem law_6 : CorrectedLaw 6 :=
  law_of_vals 6 282653756112686336975107 60 924 (-21764339220676847947083239 / 777600000)
    (by decide) (by decide) pn_val_6 (by norm_num)

end Cbcert.FiniteLaw
