import Cbcert.FiniteLaw

/-! # L5 corrected-law verification at `n = 7`.

Auto-generated by `scripts/l5_gen.py` (exact-arithmetic witnesses).
Witness `M = 1943134029034501683669931576701` (31 digits); `d_7 = 420`, `C(2·7,7) = 3432`.
`law_7` upgrades `Main.pn_valuation`'s disjunct to the sharp form at `n = 7`
(via `pn_ne_zero_7`). Do not edit by hand. -/

namespace Cbcert.FiniteLaw

open Cbcert

set_option maxHeartbeats 400000000
set_option maxRecDepth 8000

/-- Canonical `pn 7`, kernel-reduced from the `Bseries`/`acoeff` construction. -/
theorem pn_val_7 : pn 7 = 30874240683548193418311135052027 / 726062400000 := by eval_pn

/-- `pn 7 ≠ 0` — sharp-disjunct upgrade for `Main.pn_valuation` at `n = 7`. -/
theorem pn_ne_zero_7 : pn 7 ≠ 0 := by rw [pn_val_7]; norm_num

/-- The corrected law `12·d_7⁵·P_7 = 1943134029034501683669931576701 ∈ ℤ`. -/
theorem law_7 : CorrectedLaw 7 :=
  law_of_vals 7 1943134029034501683669931576701 420 3432 (30874240683548193418311135052027 / 726062400000)
    (by decide) (by decide) pn_val_7 (by norm_num)

end Cbcert.FiniteLaw
