import Cbcert.FiniteLaw

/-! # L5 corrected-law verification at `n = 8`.

Auto-generated by `scripts/l5_gen.py` (exact-arithmetic witnesses).
Witness `M = 26675673032784516788049747232207097` (35 digits); `d_8 = 840`, `C(2·8,8) = 12870`.
`law_8` upgrades `Main.pn_valuation`'s disjunct to the sharp form at `n = 8`
(via `pn_ne_zero_8`). Do not edit by hand. -/

namespace Cbcert.FiniteLaw

open Cbcert

set_option maxHeartbeats 400000000
set_option maxRecDepth 8000

/-- Canonical `pn 8`, kernel-reduced from the `Bseries`/`acoeff` construction. -/
theorem pn_val_8 : pn 8 = -544945891955455128670159122029373553 / 7965941760000 := by eval_pn

/-- `pn 8 ≠ 0` — sharp-disjunct upgrade for `Main.pn_valuation` at `n = 8`. -/
theorem pn_ne_zero_8 : pn 8 ≠ 0 := by rw [pn_val_8]; norm_num

/-- The corrected law `12·d_8⁵·P_8 = 26675673032784516788049747232207097 ∈ ℤ`. -/
theorem law_8 : CorrectedLaw 8 :=
  law_of_vals 8 26675673032784516788049747232207097 840 12870 (-544945891955455128670159122029373553 / 7965941760000)
    (by decide) (by decide) pn_val_8 (by norm_num)

end Cbcert.FiniteLaw
